//
//  PlayerInteractor.swift
//  Spotify_Clone
//
//  Created by zs-mac-3 on 01/11/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PlayerBusinessLogic
{
  func doSomething(request: Player.Something.Request)
}

protocol PlayerDataStore
{
  //var name: String { get set }
}

class PlayerInteractor: PlayerBusinessLogic, PlayerDataStore
{
  var presenter: PlayerPresentationLogic?
  var worker: PlayerWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Player.Something.Request)
  {
    worker = PlayerWorker()
    worker?.doSomeWork()
    
    let response = Player.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
