//
//  WellcomeInteractor.swift
//  Spotify_Clone
//
//  Created by zs-mac-3 on 01/11/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WellcomeBusinessLogic
{
  func doSomething(request: Wellcome.Something.Request)
}

protocol WellcomeDataStore
{
  //var name: String { get set }
}

class WellcomeInteractor: WellcomeBusinessLogic, WellcomeDataStore
{
  var presenter: WellcomePresentationLogic?
  var worker: WellcomeWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Wellcome.Something.Request)
  {
    worker = WellcomeWorker()
    worker?.doSomeWork()
    
    let response = Wellcome.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
