//
//  PlayListInteractor.swift
//  Spotify_Clone
//
//  Created by zs-mac-3 on 01/11/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PlayListBusinessLogic
{
  func doSomething(request: PlayList.Something.Request)
}

protocol PlayListDataStore
{
  //var name: String { get set }
}

class PlayListInteractor: PlayListBusinessLogic, PlayListDataStore
{
  var presenter: PlayListPresentationLogic?
  var worker: PlayListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: PlayList.Something.Request)
  {
    worker = PlayListWorker()
    worker?.doSomeWork()
    
    let response = PlayList.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
